# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='贴吧名称')),
                ('url', models.CharField(max_length=500, verbose_name='网址')),
                ('men_mun', models.IntegerField(verbose_name='关注人数')),
                ('topic_mun', models.IntegerField(verbose_name='贴子数')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='发贴人')),
                ('origin_content', models.TextField(verbose_name='页面原始HTML')),
                ('content', models.TextField(verbose_name='页面内容')),
                ('post_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('url', models.CharField(max_length=500, verbose_name='网址')),
            ],
        ),
    ]
