# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tieba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tieba.Tieba'),
        ),
    ]
