# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0002_topic_tieba'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='origin_response',
            field=models.BinaryField(null=True, verbose_name='原始数据'),
        ),
        migrations.AlterField(
            model_name='tieba',
            name='men_mun',
            field=models.IntegerField(default=0, verbose_name='关注人数'),
        ),
        migrations.AlterField(
            model_name='tieba',
            name='topic_mun',
            field=models.IntegerField(default=0, verbose_name='贴子数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='origin_content',
            field=models.TextField(null=True, verbose_name='页面原始HTML'),
        ),
    ]
