# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0003_auto_20171201_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.CharField(db_index=True, max_length=500, unique=True, verbose_name='网址'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['url'], name='tieba_topic_url_226d67_idx'),
        ),
    ]
